# Generated by Django 5.2.6 on 2025-09-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_venta', '0001_initial'),
        ('lotes', '0002_lotes_precio_costo_unitario_alter_lotes_codigo_lote_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='id',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_detalle_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_lotes', to='lotes.lotes'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='ventas.venta'),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalle_venta',
        ),
    ]
