# Generated by Django 5.2.6 on 2025-09-30 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_venta', '0002_remove_detalleventa_id_detalleventa_id_detalle_venta_and_more'),
        ('lotes', '0002_lotes_precio_costo_unitario_alter_lotes_codigo_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_lotes', to='lotes.lotes'),
        ),
    ]
