## Generated by Django 5.2.6 on 2025-09-30 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime # <--- Importación de datetime
# Nota: Si tu entorno detecta un error en este import, podría ser necesario usar 
# 'from datetime import datetime' en lugar de solo 'import datetime'

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # CORRECCIÓN DE FECHA 1: Se añade default
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0, 0))),
                # CORRECCIÓN DE FECHA 2: Se añade default
                ('updated_at', models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 1, 1, 0, 0, 0))),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # CORRECCIÓN DE FECHA 3: Se añade default
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0, 0))),
                # CORRECCIÓN DE FECHA 4: Se añade default
                ('updated_at', models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 1, 1, 0, 0, 0))),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empleados')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]