# Generated by Django 5.2.6 on 2025-10-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadoprofile',
            name='nombre_tipo_usuario',
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='dni',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='numero_contacto_emergencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='role',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('empleado', 'Empleado'), ('cajero', 'Cajero')], default='', max_length=20, verbose_name='Rol del empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadoprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleadoprofile',
            name='numero_empleado',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
