# Generated by Django 5.2.6 on 2025-09-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empleadoprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoprofile',
            name='apellidos',
            field=models.CharField(default='pendiente', max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='empleadoprofile',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='DNI/Cédula'),
        ),
        migrations.AlterField(
            model_name='empleadoprofile',
            name='email_personal',
            field=models.EmailField(default='pendiente', max_length=100, verbose_name='Email Personal (Opcional)'),
        ),
        migrations.AlterField(
            model_name='empleadoprofile',
            name='nombre',
            field=models.CharField(default='pendiente', max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='empleadoprofile',
            name='telefono',
            field=models.CharField(default='pendiente', max_length=20, verbose_name='Teléfono/Celular'),
        ),
    ]
