# Generated by Django 5.2.6 on 2025-10-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto'),
        ('productos', '0002_categoria_delete_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria'),
        ),
    ]
