# Generated by Django 5.2.6 on 2025-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoprofile',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
