# Generated by Django 5.2.6 on 2025-09-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tipo_movimientos', '0001_initial'),
        ('tipo_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('empleado_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to='core.empleadoprofile', verbose_name='Empleado Apertura')),
                ('empleado_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to='core.empleadoprofile', verbose_name='Empleado Cierre')),
            ],
            options={
                'verbose_name_plural': 'Cajas',
                'permissions': [('can_open_cash_register', 'Puede abrir y cerrar la caja')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDeCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='movimientos_caja.caja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleadoprofile', verbose_name='Empleado')),
                ('id_tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_movimientos.tipomovimiento', verbose_name='Tipo de Movimiento')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_pago.tipopago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
    ]
