# Generated by Django 5.2.6 on 2025-10-23 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('tipo_movimientos', '0001_initial'),
        ('tipo_pago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('closing_counted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closing_system_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difference_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empleado_apertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to='core.empleadoprofile', verbose_name='Empleado Apertura')),
                ('empleado_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to='core.empleadoprofile', verbose_name='Empleado Cierre')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cajas',
                'permissions': [('can_open_cash_register', 'Puede abrir y cerrar la caja')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDeCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE', 'Ajuste'), ('REVERSO', 'Reverso')], default='INGRESO', max_length=10)),
                ('origen', models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('DEVOLUCION', 'Devolución'), ('APERTURA', 'Apertura'), ('CIERRE', 'Cierre'), ('MANUAL', 'Manual'), ('AJUSTE_MANUAL', 'Ajuste Manual')], max_length=20, null=True)),
                ('ref_type', models.CharField(blank=True, max_length=30, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('ajuste_sign', models.CharField(blank=True, choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=3, null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('REVERTED', 'Revertido')], default='NORMAL', max_length=10)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='movimientos_caja.caja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empleadoprofile', verbose_name='Empleado')),
                ('id_tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_movimientos.tipomovimiento', verbose_name='Tipo de Movimiento')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_pago.tipopago', verbose_name='Tipo de Pago')),
                ('reversado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversa_de', to='movimientos_caja.movimientodecaja')),
                ('reversed_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversos', to='movimientos_caja.movimientodecaja')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
    ]
