# Generated by Django 5.2.6 on 2025-10-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='usuario',
        ),
    ]
