# Generated by Django 5.2.6 on 2025-10-11 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='closing_counted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='closing_system_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='difference_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='origen',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('DEVOLUCION', 'Devolución'), ('APERTURA', 'Apertura'), ('CIERRE', 'Cierre'), ('AJUSTE_MANUAL', 'Ajuste Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='ref_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='reversado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversa_de', to='movimientos_caja.movimientodecaja'),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('REVERTED', 'Revertido')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE', 'Ajuste'), ('REVERSO', 'Reverso')], default='INGRESO', max_length=10),
        ),
    ]
