# Generated by Django 5.2.6 on 2025-10-11 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_caja', '0002_caja_closing_counted_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='ajuste_sign',
            field=models.CharField(blank=True, choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='reversed_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversos', to='movimientos_caja.movimientodecaja'),
        ),
    ]
