# Generated by Django 5.2.6 on 2025-10-11 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_marca'),
        ('movimientos_caja', '0003_caja_usuario_movimientodecaja_ajuste_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='empleado_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to='core.empleadoprofile', verbose_name='Empleado Apertura'),
        ),
        migrations.AlterField(
            model_name='movimientodecaja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empleadoprofile', verbose_name='Empleado'),
        ),
    ]
