# Generated by Django 5.2.6 on 2025-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_caja', '0004_alter_caja_empleado_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodecaja',
            name='origen',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('DEVOLUCION', 'Devolución'), ('APERTURA', 'Apertura'), ('CIERRE', 'Cierre'), ('MANUAL', 'Manual'), ('AJUSTE_MANUAL', 'Ajuste Manual')], max_length=20, null=True),
        ),
    ]
