# Generated by Django 5.2.6 on 2025-09-30 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0002_alter_empleadoprofile_created_at_and_more'),
        ('tipo_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Venta')),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la Venta')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleados', verbose_name='Empleado')),
                ('tipo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_pago.tipopago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
