# Generated by Django 5.2.6 on 2025-09-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('movimientos_caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos_caja.caja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleadoprofile')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'permissions': [('can_view_sale_details', 'Puede ver los detalles de cualquier venta')],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
