# Generated by Django 5.2.6 on 2025-10-12 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_activo_clientes_condicion_iva_clientes_dni_and_more'),
        ('core', '0004_producto_marca'),
        ('lotes', '0004_alter_lote_proveedor'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='detalleventa',
                    name='descuento_por_item',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='detalleventa',
                    name='id_lote',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalles', to='lotes.lote'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='detalleventa',
                    name='id_producto',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalles', to='core.producto'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='venta',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empleadoprofile'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
