# Generated by Django 5.2.6 on 2025-10-12 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_marca'),
        ('ventas', '0002_detalleventa_descuento_por_item_detalleventa_id_lote_and_more'),
    ]

    operations = [
        # Evitar aplicar defaults erróneos en la base (solo actualizar estado del modelo)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='detalleventa',
                    name='id_producto',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalles', to='core.producto'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='venta',
                    name='medio_pago',
                    field=models.CharField(max_length=20),
                ),
            ],
        ),
    ]
