# Generated by Django 5.2.6 on 2025-09-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
