# Generated by Django 5.2.6 on 2025-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
