# Generated by Django 5.2.6 on 2025-10-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0002_marca_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
