# Generated by Django 5.2.6 on 2025-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_compra', '0002_alter_detallecompra_id_producto'),
        ('detalles_venta', '0002_alter_detalleventa_id_producto'),
        ('lotes', '0002_alter_lotes_id_producto'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
