# Generated by Django 5.2.6 on 2025-10-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='condicion_iva',
            field=models.CharField(blank=True, choices=[('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('MT', 'Monotributo'), ('EX', 'Exento'), ('NR', 'No Responsable')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
