# Generated by Django 5.2.6 on 2025-10-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre_completo',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='apellidorandom', max_length=100),
            preserve_default=False,
        ),
    ]
