# Generated by Django 5.2.6 on 2025-10-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_created_at_clientes_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='clientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
