# Generated by Django 5.2.6 on 2025-10-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='proveedor',
        ),
    ]
