# Generated by Django 5.2.6 on 2025-10-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
