# Generated by Django 5.2.6 on 2025-10-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='compras.compras'),
        ),
    ]
