# Generated by Django 5.2.6 on 2025-09-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='precio_costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lotes',
            name='codigo_lote',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='lotes',
            table='Lotes',
        ),
    ]
