# Generated by Django 5.2.6 on 2025-10-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_alter_lote_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
