# Generated by Django 5.2.6 on 2025-09-30 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('tipo_pago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de la Compra')),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedores', verbose_name='Proveedor')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_pago.tipopago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
