# Generated by Django 5.2.6 on 2025-10-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_detalles', to='lotes.lote'),
        ),
    ]
