# Generated by Django 5.2.6 on 2025-10-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='cuil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
