# Generated by Django 5.2.6 on 2025-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedores_cuil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='nombre_proveedor',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='teléfono',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
