# Generated by Django 5.2.6 on 2025-10-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_rename_nombre_proveedor_proveedores_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
