# Generated by Django 5.2.6 on 2025-09-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('lotes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_de_compra_app', to='compras.compras', verbose_name='Compra')),
                ('id_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra_lotes', to='lotes.lotes', verbose_name='Lote Asociado')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_de_producto_app', to='productos.productos', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'detalle_compra',
            },
        ),
    ]
