# Generated by Django 5.2.6 on 2025-09-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_compra', '0001_initial'),
        ('lotes', '0002_lotes_precio_costo_unitario_alter_lotes_codigo_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='id_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra_lotes', to='lotes.lotes'),
        ),
        migrations.AlterModelTable(
            name='detallecompra',
            table='detalle_compra',
        ),
    ]
