# Generated by Django 5.2.6 on 2025-09-30 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_compra', '0002_detallecompra_id_lote_alter_detallecompra_table'),
        ('lotes', '0002_lotes_precio_costo_unitario_alter_lotes_codigo_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra_lotes', to='lotes.lotes'),
        ),
    ]
